GET http://localhost:13000/api/t_9mgrdqjcrvg:list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGVOYW1lIjoiZG9jX0FQSSIsImlhdCI6MTc3MjA3NzM1OSwiZXhwIjozMzMyOTY3NzM1OX0.ceNC6lvl9mTnz79pu2r52R946aWHMoSnr9t37l4p1yc